os: Visual Studio 2017
platform: x64

build_script:

   - mkdir build_msbuild
   - cd build_msbuild
   - cmake -G "Visual Studio 15 2017 Win64" ..
   - msbuild audition-project-devops-kalmeep-master.sln
   - ctest
   - cd..

